# -*- coding: utf-8 -*-
"""rfm_customer_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dyW7ddI-ba7JFH0dYiuNsbmZbIcCs25d
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

df = pd.read_csv('/content/online_retail_clean.csv')

df.head()

df.info()
df.describe()

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

df.info()

# Remove cancelled or invalid transactions
df = df[df['Quantity'] > 0]

# Remove missing customer IDs
df = df[df['Customer_ID'].notna()]

# Convert date column
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

# Create Revenue column
df['Revenue'] = df['Quantity'] * df['Price']

df.head()

df.describe()
df.isnull().sum()

customer_df = df.groupby('Customer_ID').agg(
    Total_Revenue=('Revenue', 'sum'),
    Total_Orders=('Invoice', 'nunique'),
    Total_Quantity=('Quantity', 'sum'),
    First_Purchase=('InvoiceDate', 'min'),
    Last_Purchase=('InvoiceDate', 'max')
).reset_index()

customer_df.head()

customer_df.info()
customer_df.describe()

"""day 2"""

customer_df = customer_df.sort_values(by='Total_Revenue', ascending=False)

customer_df.head()

"""Calculate Revenue Contribution Percentage"""

total_revenue = customer_df['Total_Revenue'].sum()
total_revenue

customer_df['Revenue_Percentage'] = (
    customer_df['Total_Revenue'] / total_revenue
) * 100

customer_df.head()

"""Cumulative Revenue (Pareto Analysis)"""

customer_df['Cumulative_Revenue_Percentage'] = (
    customer_df['Revenue_Percentage'].cumsum()
)

customer_df.head()

"""Identify Top 20% Customers"""

top_20_percent_count = int(0.2 * len(customer_df))
top_20_percent_count

top_20_revenue_share = customer_df.head(top_20_percent_count)['Revenue_Percentage'].sum()

top_20_revenue_share

"""Visualize Revenue Distribution"""

plt.figure(figsize=(8,5))
sns.histplot(customer_df['Total_Revenue'], bins=50)
plt.title("Customer Revenue Distribution")
plt.show()

top_20_percent_count = int(0.2 * len(customer_df))
top_20_revenue_share = customer_df.head(top_20_percent_count)['Revenue_Percentage'].sum()

top_20_revenue_share

plt.figure(figsize=(8,5))
sns.histplot(customer_df['Total_Revenue'], bins=50)
plt.xlim(0, 2000)
plt.title("Customer Revenue Distribution (Zoomed)")
plt.show()

"""Create Customer Segments (Rule-Based)"""

def segment_customer(row):
    if row['Total_Revenue'] > 500:
        return "High Value"
    elif row['Total_Revenue'] > 100:
        return "Mid Value"
    else:
        return "Low Value"

customer_df['Customer_Segment'] = customer_df.apply(segment_customer, axis=1)

customer_df.head()

"""Segment Revenue Contribution"""

segment_summary = customer_df.groupby('Customer_Segment').agg(
    Customers=('Customer_ID', 'count'),
    Total_Revenue=('Total_Revenue', 'sum')
).reset_index()

segment_summary

"""Segment Revenue Percentage"""

segment_summary['Revenue_Percentage'] = (
    segment_summary['Total_Revenue'] / total_revenue
) * 100

segment_summary

"""segmentation logic using quartiles

Revenue Quartiles
"""

customer_df['Total_Revenue'].describe()

"""Create Quartile-Based Segmentation"""

customer_df['Revenue_Segment'] = pd.qcut(
    customer_df['Total_Revenue'],
    q=4,
    labels=['Low Value', 'Mid Value', 'High Value', 'Top Value']
)

customer_df['Revenue_Segment'].value_counts()

"""Segment Revenue Summary"""

segment_summary = customer_df.groupby('Revenue_Segment').agg(
    Customers=('Customer_ID', 'count'),
    Total_Revenue=('Total_Revenue', 'sum')
).reset_index()

segment_summary['Revenue_Percentage'] = (
    segment_summary['Total_Revenue'] / total_revenue
) * 100

segment_summary

"""Pareto Curve (Cumulative Revenue %)"""

customer_df_sorted = customer_df.sort_values(by='Total_Revenue', ascending=False)
customer_df_sorted['Cumulative_Revenue'] = customer_df_sorted['Total_Revenue'].cumsum()
customer_df_sorted['Cumulative_Percentage'] = (
    customer_df_sorted['Cumulative_Revenue'] / total_revenue
) * 100

plt.figure(figsize=(8,5))
plt.plot(customer_df_sorted['Cumulative_Percentage'].values)
plt.axhline(80, linestyle='--')
plt.title("Pareto Analysis – Cumulative Revenue Contribution")
plt.ylabel("Cumulative Revenue (%)")
plt.xlabel("Customers Ranked by Revenue")
plt.show()

"""day 3

Revenue by Segment
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))
sns.barplot(data=segment_summary, x='Revenue_Segment', y='Revenue_Percentage')
plt.title("Revenue Contribution by Customer Segment")
plt.ylabel("Revenue Percentage (%)")
plt.show()

"""Key Findings

Revenue distribution is heavily right-skewed.

Top 20% customers generate 77.8% of total revenue.

The top quartile (Top Value segment) contributes disproportionately to total sales.

Revenue concentration indicates strong dependency on high-value customers.

Business Implications

Retention strategies should prioritize Top Value customers.

Loyalty incentives can increase lifetime value.

Mid-tier customers represent growth opportuni

RFM Segmentation (Industry Standard)
"""

analysis_date = df['InvoiceDate'].max()

customer_df['Recency_Days'] = (
    analysis_date - customer_df['Last_Purchase']
).dt.days

customer_df.head()

"""RFM Scoring (Quartile-Based)

Create Analysis Date & Recency
"""

# Reference date (latest transaction date)
analysis_date = df['InvoiceDate'].max()

# Calculate Recency (days since last purchase)
customer_df['Recency_Days'] = (
    analysis_date - customer_df['Last_Purchase']
).dt.days

"""Create RFM Scores (Handling Duplicates Properly)"""

import pandas as pd

# Recency Score (Lower Recency = Better → reverse labels)
customer_df['R_Score'] = pd.qcut(
    customer_df['Recency_Days'],
    4,
    labels=[4,3,2,1]
)

# Frequency Score (Handle duplicate edges issue)
customer_df['F_Score'] = pd.qcut(
    customer_df['Total_Orders'].rank(method='first'), # Fixed: Using .rank(method='first')
    4,
    labels=[1,2,3,4]
)

# Monetary Score
customer_df['M_Score'] = pd.qcut(
    customer_df['Total_Revenue'],
    4,
    labels=[1,2,3,4]
)

"""Combine into RFM Score"""

customer_df['RFM_Score'] = (
    customer_df['R_Score'].astype(str) +
    customer_df['F_Score'].astype(str) +
    customer_df['M_Score'].astype(str)
)

customer_df[['Customer_ID','Recency_Days','Total_Orders','Total_Revenue','RFM_Score']].head()

"""Create Business-Friendly RFM Segments"""

def rfm_segment(row):

    if row['RFM_Score'] == '444':
        return 'Champions'

    elif row['M_Score'] == 4:
        return 'High Value'

    elif int(row['F_Score']) >= 3:
        return 'Loyal Customers'

    elif int(row['R_Score']) == 4:
        return 'Recent Customers'

    else:
        return 'Standard Customers'

customer_df['RFM_Segment'] = customer_df.apply(rfm_segment, axis=1)

"""RFM Summary Table"""

rfm_summary = customer_df.groupby('RFM_Segment').agg(
    Customers=('Customer_ID','count'),
    Total_Revenue=('Total_Revenue','sum')
).reset_index()

# Calculate revenue percentage
rfm_summary['Revenue_Percentage'] = (
    rfm_summary['Total_Revenue'] / total_revenue
) * 100

rfm_summary.sort_values(by='Revenue_Percentage', ascending=False)

"""Visualize RFM Revenue Contribution"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))
sns.barplot(data=rfm_summary, x='RFM_Segment', y='Revenue_Percentage')
plt.title("Revenue Contribution by RFM Segment")
plt.ylabel("Revenue Percentage (%)")
plt.xticks(rotation=45)
plt.show()